name: uptime

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Or any version you prefer
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run website check
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          PREVIOUSLY_DOWN: false # Initialize
        run: python uptime.py