name: Website Uptime Check

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:  # Manual trigger option

jobs:
  uptime-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run uptime check script
      env:
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python scripts/check_uptime.py

    - name: Commit and push log updates
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update uptime log